### PR TITLE
Cleanup runtime error when assigning to a smaller container

### PR DESCRIPTION
**Pull request by jgfoster**
On my local build this passes all the tests with the Runtime configuration.
From my understanding of the compiler behavior, adding the mask (x & 0xFF) does not impact performance since the value is immediately subject to a cast that would do the same thing. This just makes it explicit to avoid the runtime error.
This does expose a possible issue (to be filed separately) in Compiler::GenInstructionExtended().

### CODE REVIEW

**Comment by objectarts** [comment]
@jgfoster, I think we should fix #19 first before applying this PR.

**Comment by jgfoster** [comment]
My thought was that since the (potential) bug is already in the master branch, the Debug configuration will hit a break *every time* through this method because of the *existing* runtime checks for truncation. With this commit we *reduce* the noise in the Debug configuration and hit the break *only* in the rare cases when the existing truncation might cause a problem. The Release configuration is unaffected both before and after (containing the silent truncation), so the only impact of this commit is to eliminate dropping into the debugger unnecessarily.

Of course, I can run with this code locally so I don't mind if you would prefer to wait. Thanks for looking and commenting.

**Comment by objectarts** [comment]
Ok, in that case, have merged.

**Comment by blairmcg** [comment]
@jgfoster, sorry to be here after the fact, but I think parts of this should be reverted and the underlying cause investigated. It doesn't make sense to pass ints to the bytecode generation instructions as the values should always be in the 0.255 range. If some truncation is happening somewhere, then there is a compiler bug that will be generating incorrect code.

**Comment by jgfoster** [comment]
@blairmcg, the only behavior change in this pull request was to *expose* the preexisting bug and cause an assert in a debug configuration when the truncation would actually occur. What benefit do you see in reverting this commit and re-hiding the underlying bug?

**Comment by blairmcg** [comment]
@jgfoster, the contract of (for example) Compiler::GenInstructionExtended(BYTE basic, int extension) is now wrong. The extension can only ever be a byte value. It would be better to enable the compiler warning for integer truncation and then look at the offending callers. But don't worry, I wasn't suggesting that you do it, just that I might. I wouldn't change those parts back without fixing the underlying bug, as there is no point in that.

**Comment by jgfoster** [comment]
@blairmcg, I see now. The reason I changed the contract was because *every* caller was passing an `int` and it was easier to do the truncation check in one place.

**Pull request merged**
