### PR TITLE
Blairmc/vs2015vm

### PR DESCRIPTION
**Pull request by blairmcg**
Complete the VS2015 migration of the VM

### CODE REVIEW

**Comment by blairmcg** [comment]
Hmmm, a build from VS2015 is exposing a hidden bug in the Dolphin VM when running on x64 platforms (i.e. running as a 32-bit app under WoW64). The quit primitive works by throwing an SEH exception that is handled in the main "run" entry point of the interpreter. However, if this is done inside a "callback" that has transitioned through kernel mode, e.g. as a result of a windows message send such as that to process a command, then the attempt to throw the exception across the user/kernel mode boundary will fail. I suspect that in VS2013 the exception may have been silently suppressed as explained [here](http://blog.paulbetts.org/index.php/2010/07/20/the-case-of-the-disappearing-onload-exception-user-mode-callback-exceptions-in-x64/). Dolphin would exit anyway even when the exception is silently suppressed and the image continues to run, because the SessionManager>>quit method has closed all the windows, which is then detected and another successful attempt is made to exit. Debugging through in the VS2015 built VM it looks like the exit exception is being caught at the callback boundary and translated into a different (unhandled) exception.
When Dolphin's VM was originally written we were using 32-bit versions of Windows, under which exceptions were allowed to transit through kernel mode. Dolphin throws an exception to try and exit cleanly (because native stack unwind handlers will be run, allowing cleanup to be performed). 
This mechanism now needs to be changed so that any callbacks into the image are unwound _before _the SEH exception is raised to shutdown the interpreter. Such a change will probably require a further push to the Dolphin repo before this PR can be completed.

**Comment by fxgallego** [comment]
I don't know if the following is related to this but only to take into account.

In a 6.1 Beta 2 image, evaluating "SessionManager current primQuit: 0" causes Dolphin to die and a Windows notice about Dolphin has stopped working (Not sure if it's the right msg because my win is spanish). I'm not sure if this should be considered as normal behavior.

**Comment by blairmcg** [comment]
Interesting @fxgallego. What happens if you execute "SessonManager current quit<Ctrl+D>"?
What about "[SessionManager current quit] postToInputQueue<Ctrl+D>"?
If the quit executed directly crashes, but the posted one does not, then that is a demonstration of the problem of attempting to throw an exception across the user/kernel mode boundary. The posted version allows the callbacks to unwind, so there are no kernel mode frames on the stack when the exception is thrown.

**Comment by fxgallego** [comment]
@blairmcg The first one "SessionManager current quit" exits ok (no windows notice) but the following .errors file is generated:
`********************************************************************************
************************** Dolphin Crash Dump Report ***************************

18:50:29 p. m., 1/2/2016: Dolphin.exe caused an unhandled Win32 Exception A0000204
at 7611D8A8 in module 76060000 (C:\WINDOWS\SYSTEM32\KERNELBASE.dll)

*----> Exception Parameters <----*
00000000	

*----> CPU Context for thread 0x2184 <----*
EAX = 00C0F9E0 EBX = 05D00670 ECX = 00000001
ESI = 05D00690 EDI = 026132F4 EIP = 7611D8A8
ESP = 00C0F9E0 EBP = 00C0FA3C EFL = 00000212
CS = 0023 SS = 002B DS = 002B
ES = 002B FS = 0053 GS = 002B

*----> VM Context <----*
Process: {05D00004:size 702 words, suspended frame 05D00AE1, priority 5, callbacks 1
last failure 0:nil, FPE mask 3, thread 00000000}
Active Method: SessionManager>>quit:
IP: 026132F4 (4)
SP: 05D00690
BP: 05D00670 (396)
ActiveFrame: {05D00674: cf 05D00655, sp 05D00688, bp 05D00670, ip 2, DevelopmentSessionManager(SessionManager)>>quit:}
	receiver: a DevelopmentSessionManager
	arg[0]: 0


New Method: SessionManager>>primQuit:
Message Selector: primQuit:

*----> Stack Back Trace <----*
{05D00674: cf 05D00655, sp 05D00688, bp 05D00670, ip 2, DevelopmentSessionManager(SessionManager)>>quit:}
	receiver: a DevelopmentSessionManager
	arg[0]: 0

{05D00654: cf 05D00639, sp 05D00668, bp 05D00654, ip 4, DevelopmentSessionManager(SessionManager)>>quit}
	receiver: a DevelopmentSessionManager

{05D00638: cf 05D0061D, sp 05D0064C, bp 05D00638, ip 4, UndefinedObject>>???'doIt'}
	receiver: nil

{05D0061C: cf 05D005FD, sp 05D00630, bp 05D00618, ip 4, CompiledExpression>>value:}
	receiver: a CompiledExpression
	arg[0]: nil

{05D005FC: cf 05D005CD, sp 05D00610, bp 05D005E8, ip 28, SmalltalkWorkspace>>evaluateRange:ifFail:debug:}
	receiver: a SmalltalkWorkspace
	arg[0]: a Interval
	arg[1]: [] @ 12 in SmalltalkWorkspace>>evaluateItIfFail:debug:
	arg[2]: false
	stack temp[0]: a CompilationResult
	stack temp[1]: nil

{05D005CC: cf 05D0059D, sp 05D005E0, bp 05D005B8, ip 18, SmalltalkWorkspace>>evaluateItIfFail:debug:}
	receiver: a SmalltalkWorkspace
	arg[0]: [] @ 3 in UndefinedObject>>???'doIt'
	arg[1]: false
	stack temp[0]: a Interval
	stack temp[1]: nil
	stack temp[2]: nil

{05D0059C: cf 05D0057D, sp 05D005B0, bp 05D00598, ip 4, SmalltalkWorkspace>>evaluateItIfFail:}
	receiver: a SmalltalkWorkspace
	arg[0]: [] @ 3 in UndefinedObject>>???'doIt'

{05D0057C: cf 05D00561, sp 05D00590, bp 05D0057C, ip 4, SmalltalkWorkspace>>evaluateIt}
	receiver: a SmalltalkWorkspace

{05D00560: cf 05D00541, sp 05D00574, bp 05D0055C, ip 4, Symbol>>forwardTo:}
	receiver: evaluateIt
	arg[0]: a SmalltalkWorkspace

{05D00540: cf 05D00521, sp 05D00554, bp 05D0053C, ip 4, CommandDescription>>performAgainst:}
	receiver: a CommandDescription
	arg[0]: a SmalltalkWorkspace

{05D00520: cf 05D004FD, sp 05D00534, bp 05D00520, ip 14, [] in Command>>value}
	receiver: a Command

{05D004FC: cf 05D004DD, sp 05D00510, bp 05D004F8, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 17 in Command>>value

{05D004DC: cf 05D004B9, sp 05D004F0, bp 05D004D4, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in Command>>value
	arg[0]: [] @ 17 in Command>>value
	stack temp[0]: nil

{05D004B8: cf 05D0049D, sp 05D004CC, bp 05D004B8, ip 22, Command>>value}
	receiver: a Command

{05D0049C: cf 05D0047D, sp 05D004B0, bp 05D00498, ip 30, ShellView>>performCommand:}
	receiver: a ShellView
	arg[0]: a Command

{05D0047C: cf 05D0045D, sp 05D00490, bp 05D00478, ip 4, SmalltalkWorkspaceDocument(Shell)>>performCommand:}
	receiver: a SmalltalkWorkspaceDocument
	arg[0]: a Command

{05D0045C: cf 05D00435, sp 05D00470, bp 05D00450, ip 10, CommandQuery>>perform}
	receiver: a CommandQuery
	stack temp[0]: a Command
	stack temp[1]: nil
	stack temp[2]: a SmalltalkWorkspaceDocument

{05D00434: cf 05D00411, sp 05D00448, bp 05D0042C, ip 8, DelegatingCommandPolicy(CommandPolicy)>>route:}
	receiver: a DelegatingCommandPolicy
	arg[0]: a CommandDescription
	stack temp[0]: a CommandQuery

{05D00410: cf 05D003E9, sp 05D00424, bp 05D0040C, ip 15, [] in ShellView(View)>>onCommand:}
	receiver: a ShellView

{05D003E8: cf 05D003C9, sp 05D003FC, bp 05D003E4, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 18 in Cursor>>showWhile:

{05D003C8: cf 05D003A5, sp 05D003DC, bp 05D003C0, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 11 in View>>onCommand:
	arg[0]: [] @ 18 in Cursor>>showWhile:
	stack temp[0]: nil

{05D003A4: cf 05D0037D, sp 05D003B8, bp 05D00398, ip 27, Cursor>>showWhile:}
	receiver: a Cursor
	arg[0]: [] @ 11 in View>>onCommand:
	stack temp[0]: nil
	stack temp[1]: a ExternalHandle(00010005)

{05D0037C: cf 05D00359, sp 05D00390, bp 05D00374, ip 17, ShellView(View)>>onCommand:}
	receiver: a ShellView
	arg[0]: a CommandDescription
	stack temp[0]: nil

{05D00358: cf 05D00325, sp 05D0036C, bp 05D00340, ip 19, ShellView(View)>>wmCommand:wParam:lParam:}
	receiver: a ShellView
	arg[0]: 273
	arg[1]: 72954
	arg[2]: 0
	stack temp[0]: 7418
	stack temp[1]: a CommandDescription
	stack temp[2]: nil

{05D00324: cf 05D002F5, sp 05D00338, bp 05D00310, ip 23, ShellView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ShellView
	arg[0]: 273
	arg[1]: 72954
	arg[2]: 0
	stack temp[0]: nil
	stack temp[1]: wmCommand:wParam:lParam:

{05D002F4: cf 05D002C1, sp 05D00308, bp 05D002E4, ip 70, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{05D002C0: cf 05D00299, sp 05D002D4, bp 05D002BC, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 11 in ProcessorScheduler>>callback:evaluate:

{05D00298: cf 05D00275, sp 05D002B4, bp 05D00290, ip 15, ProcessorScheduler>>callback:evaluate:}
	receiver: a ProcessorScheduler
	arg[0]: 6323544
	arg[1]: [] @ 64 in InputState>>wndProc:message:wParam:lParam:cookie:

{05D00274: cf 05D00231, sp 05D00288, bp 05D0025C, ip 73, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 329498
	arg[1]: 273
	arg[2]: 72954
	arg[3]: 0
	arg[4]: 6323544
	stack temp[0]: a ShellView

{05D00230: cf 05D0020D, sp 05D00254, bp 05D00228, ip 17, ShellView>>translateAccelerator:}
	receiver: a ShellView
	arg[0]: a MSG
	stack temp[0]: a ExternalHandle(00D005C1)

{05D0020C: cf 05D001E9, sp 05D00220, bp 05D00204, ip 6, ShellView>>preTranslateKeyboardInput:}
	receiver: a ShellView
	arg[0]: a MSG
	stack temp[0]: nil

{05D001E8: cf 05D001C9, sp 05D001FC, bp 05D001E4, ip 6, ShellView(View)>>preTranslateMessage:}
	receiver: a ShellView
	arg[0]: a MSG

{05D001C8: cf 05D001A1, sp 05D001DC, bp 05D001BC, ip 17, InputState>>preTranslateMessage:}
	receiver: a InputState
	arg[0]: a MSG
	stack temp[0]: 329498
	stack temp[1]: a ShellView

{05D001A0: cf 05D00181, sp 05D001B4, bp 05D0019C, ip 19, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{05D00180: cf 05D00155, sp 05D00194, bp 05D00170, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: [] @ 9 in SessionManager>>forkMain

{05D00154: cf 05D00139, sp 05D00168, bp 05D00154, ip 15, InputState>>mainLoop}
	receiver: a InputState

{05D00138: cf 05D0011D, sp 05D0014C, bp 05D00138, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{05D0011C: cf 05D00101, sp 05D00130, bp 05D0011C, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{05D00100: cf 05D000D9, sp 05D00114, bp 05D000FC, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{05D000D8: cf 05D000B9, sp 05D000EC, bp 05D000D4, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{05D000B8: cf 05D00095, sp 05D000CC, bp 05D000B0, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{05D00094: cf 05D0006D, sp 05D000A8, bp 05D00088, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 05D00000 [ACTIVE] in SessionManager>>quit: sp=00000000 ip=1 list=10050010)
	env temp[0]: nil

{05D0006C: cf 05D00049, sp 05D00080, bp 05D00064, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{05D00048: cf 00000001, sp 05D0005C, bp 05D00048, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

*----> Stack <----*
[05D00690: 404]-->0
[05D0068C: 403]-->a DevelopmentSessionManager
[05D00688: 402]-->48759608
[05D00684: 401]-->48759620
[05D00680: 400]-->1
[05D0067C: 399]-->48759594
[05D00678: 398]-->0
[05D00674: 397]-->SessionManager>>quit:
[05D00670: 396]-->0
[05D0066C: 395]-->a DevelopmentSessionManager
[05D00668: 394]-->48759594
[05D00664: 393]-->48759604
[05D00660: 392]-->3
[05D0065C: 391]-->48759580
[05D00658: 390]-->0
[05D00654: 389]-->SessionManager>>quit
[05D00650: 388]-->a DevelopmentSessionManager
[05D0064C: 387]-->48759580
[05D00648: 386]-->48759590
[05D00644: 385]-->3
[05D00640: 384]-->48759566
[05D0063C: 383]-->0
[05D00638: 382]-->a CompiledExpression
[05D00634: 381]-->nil
[05D00630: 380]-->48759564
[05D0062C: 379]-->48759576
[05D00628: 378]-->3
[05D00624: 377]-->48759550
[05D00620: 376]-->0
[05D0061C: 375]-->CompiledExpression>>value:
[05D00618: 374]-->nil
[05D00614: 373]-->a CompiledExpression
[05D00610: 372]-->48759540
[05D0060C: 371]-->48759560
[05D00608: 370]-->27
[05D00604: 369]-->48759526
[05D00600: 368]-->0
[05D005FC: 367]-->SmalltalkWorkspace>>evaluateRange:ifFail:debug:
[05D005F8: 366]-->nil
[05D005F4: 365]-->a CompilationResult
[05D005F0: 364]-->false
[05D005EC: 363]-->[] @ 12 in SmalltalkWorkspace>>evaluateItIfFail:debug:
[05D005E8: 362]-->a Interval
[05D005E4: 361]-->a SmalltalkWorkspace
[05D005E0: 360]-->48759516
[05D005DC: 359]-->48759536
[05D005D8: 358]-->17
[05D005D4: 357]-->48759502
[05D005D0: 356]-->a Context for: nil frame: 5d005cd
[05D005CC: 355]-->SmalltalkWorkspace>>evaluateItIfFail:debug:
[05D005C8: 354]-->nil
[05D005C4: 353]-->nil
[05D005C0: 352]-->a Interval
[05D005BC: 351]-->false
[05D005B8: 350]-->[] @ 3 in UndefinedObject>>???'doIt'
[05D005B4: 349]-->a SmalltalkWorkspace
[05D005B0: 348]-->48759500
[05D005AC: 347]-->48759512
[05D005A8: 346]-->3
[05D005A4: 345]-->48759486
[05D005A0: 344]-->0
[05D0059C: 343]-->SmalltalkWorkspace>>evaluateItIfFail:
[05D00598: 342]-->[] @ 3 in UndefinedObject>>???'doIt'
[05D00594: 341]-->a SmalltalkWorkspace
[05D00590: 340]-->48759486
[05D0058C: 339]-->48759496
[05D00588: 338]-->3
[05D00584: 337]-->48759472
[05D00580: 336]-->0
[05D0057C: 335]-->SmalltalkWorkspace>>evaluateIt
[05D00578: 334]-->a SmalltalkWorkspace
[05D00574: 333]-->48759470
[05D00570: 332]-->48759482
[05D0056C: 331]-->3
[05D00568: 330]-->48759456
[05D00564: 329]-->0
[05D00560: 328]-->Symbol>>forwardTo:
[05D0055C: 327]-->a SmalltalkWorkspace
[05D00558: 326]-->evaluateIt
[05D00554: 325]-->48759454
[05D00550: 324]-->48759466
[05D0054C: 323]-->3
[05D00548: 322]-->48759440
[05D00544: 321]-->0
[05D00540: 320]-->CommandDescription>>performAgainst:
[05D0053C: 319]-->a SmalltalkWorkspace
[05D00538: 318]-->a CommandDescription
[05D00534: 317]-->48759440
[05D00530: 316]-->48759450
[05D0052C: 315]-->13
[05D00528: 314]-->48759422
[05D00524: 313]-->[] @ 11 in Command>>value
[05D00520: 312]-->Command>>value
[05D0051C: 311]-->a Command
[05D00518: 310]-->[] @ 9 in BlockClosure>>ifCurtailed:
[05D00514: 309]-->[] @ 11 in Command>>value
[05D00510: 308]-->48759420
[05D0050C: 307]-->48759432
[05D00508: 306]-->17
[05D00504: 305]-->48759406
[05D00500: 304]-->0
[05D004FC: 303]-->BlockClosure>>ifCurtailed:
[05D004F8: 302]-->[] @ 17 in Command>>value
[05D004F4: 301]-->[] @ 0 in nil
[05D004F0: 300]-->48759402
[05D004EC: 299]-->48759416
[05D004E8: 298]-->2
[05D004E4: 297]-->48759388
[05D004E0: 296]-->0
[05D004DC: 295]-->BlockClosure>>ensure:
[05D004D8: 294]-->nil
[05D004D4: 293]-->[] @ 17 in Command>>value
[05D004D0: 292]-->[] @ 11 in Command>>value
[05D004CC: 291]-->48759388
[05D004C8: 290]-->48759398
[05D004C4: 289]-->21
[05D004C0: 288]-->48759374
[05D004BC: 287]-->0
[05D004B8: 286]-->Command>>value
[05D004B4: 285]-->a Command
[05D004B0: 284]-->48759372
[05D004AC: 283]-->48759384
[05D004A8: 282]-->29
[05D004A4: 281]-->48759358
[05D004A0: 280]-->0
[05D0049C: 279]-->ShellView>>performCommand:
[05D00498: 278]-->a Command
[05D00494: 277]-->a ShellView
[05D00490: 276]-->48759356
[05D0048C: 275]-->48759368
[05D00488: 274]-->3
[05D00484: 273]-->48759342
[05D00480: 272]-->0
[05D0047C: 271]-->Shell>>performCommand:
[05D00478: 270]-->a Command
[05D00474: 269]-->a SmalltalkWorkspaceDocument
[05D00470: 268]-->48759336
[05D0046C: 267]-->48759352
[05D00468: 266]-->9
[05D00464: 265]-->48759322
[05D00460: 264]-->0
[05D0045C: 263]-->CommandQuery>>perform
[05D00458: 262]-->a SmalltalkWorkspaceDocument
[05D00454: 261]-->nil
[05D00450: 260]-->a Command
[05D0044C: 259]-->a CommandQuery
[05D00448: 258]-->48759318
[05D00444: 257]-->48759332
[05D00440: 256]-->7
[05D0043C: 255]-->48759304
...
<103 slots omitted>
...
[05D0029C: 151]-->0
[05D00298: 150]-->ProcessorScheduler>>callback:evaluate:
[05D00294: 149]-->[] @ 64 in InputState>>wndProc:message:wParam:lParam:cookie:
[05D00290: 148]-->6323544
[05D0028C: 147]-->a ProcessorScheduler
[05D00288: 146]-->48759086
[05D00284: 145]-->48759108
[05D00280: 144]-->72
[05D0027C: 143]-->48759064
[05D00278: 142]-->0
[05D00274: 141]-->InputState>>wndProc:message:wParam:lParam:cookie:
[05D00270: 140]-->a ShellView
[05D0026C: 139]-->6323544
[05D00268: 138]-->0
[05D00264: 137]-->72954
[05D00260: 136]-->273
[05D0025C: 135]-->329498
[05D00258: 134]-->a InputState
[05D00254: 133]-->a MSG
[05D00250: 132]-->a ExternalHandle(00D005C1)
[05D0024C: 131]-->a ExternalHandle(0005071A)
[05D00248: 130]-->a UserLibrary
[05D00244: 129]-->48759060
[05D00240: 128]-->48759082
[05D0023C: 127]-->16
[05D00238: 126]-->48759046
[05D00234: 125]-->0
[05D00230: 124]-->ShellView>>translateAccelerator:
[05D0022C: 123]-->a ExternalHandle(00D005C1)
[05D00228: 122]-->a MSG
[05D00224: 121]-->a ShellView
[05D00220: 120]-->48759042
[05D0021C: 119]-->48759056
[05D00218: 118]-->5
[05D00214: 117]-->48759028
[05D00210: 116]-->0
[05D0020C: 115]-->ShellView>>preTranslateKeyboardInput:
[05D00208: 114]-->nil
[05D00204: 113]-->a MSG
[05D00200: 112]-->a ShellView
[05D001FC: 111]-->48759026
[05D001F8: 110]-->48759038
[05D001F4: 109]-->5
[05D001F0: 108]-->48759012
[05D001EC: 107]-->0
[05D001E8: 106]-->View>>preTranslateMessage:
[05D001E4: 105]-->a MSG
[05D001E0: 104]-->a ShellView
[05D001DC: 103]-->48759006
[05D001D8: 102]-->48759022
[05D001D4: 101]-->16
[05D001D0: 100]-->48758992
[05D001CC: 99]-->0
[05D001C8: 98]-->InputState>>preTranslateMessage:
[05D001C4: 97]-->a ShellView
[05D001C0: 96]-->329498
[05D001BC: 95]-->a MSG
[05D001B8: 94]-->a InputState
[05D001B4: 93]-->48758990
[05D001B0: 92]-->48759002
[05D001AC: 91]-->18
[05D001A8: 90]-->48758976
[05D001A4: 89]-->0
[05D001A0: 88]-->InputState>>pumpMessage:
[05D0019C: 87]-->a MSG
[05D00198: 86]-->a InputState
[05D00194: 85]-->48758968
[05D00190: 84]-->48758986
[05D0018C: 83]-->17
[05D00188: 82]-->48758954
[05D00184: 81]-->0
[05D00180: 80]-->InputState>>loopWhile:
[05D0017C: 79]-->[] @ 9 in SessionManager>>forkMain
[05D00178: 78]-->true
[05D00174: 77]-->a MSG
[05D00170: 76]-->[] @ 9 in InputState>>mainLoop
[05D0016C: 75]-->a InputState
[05D00168: 74]-->48758954
[05D00164: 73]-->48758964
[05D00160: 72]-->14
[05D0015C: 71]-->48758940
[05D00158: 70]-->0
[05D00154: 69]-->InputState>>mainLoop
[05D00150: 68]-->a InputState
[05D0014C: 67]-->48758940
[05D00148: 66]-->48758950
[05D00144: 65]-->13
[05D00140: 64]-->48758926
[05D0013C: 63]-->[] @ 10 in InputState>>forkMain
[05D00138: 62]-->InputState>>forkMain
[05D00134: 61]-->a InputState
[05D00130: 60]-->48758926
[05D0012C: 59]-->48758936
[05D00128: 58]-->12
[05D00124: 57]-->48758912
[05D00120: 56]-->a Context for: nil frame: 5d0011d
[05D0011C: 55]-->ExceptionHandlerAbstract>>markAndTry
[05D00118: 54]-->a ExceptionHandler
[05D00114: 53]-->48758910
[05D00110: 52]-->48758922
[05D0010C: 51]-->21
[05D00108: 50]-->48758892
[05D00104: 49]-->[] @ 17 in ExceptionHandlerAbstract>>try:
[05D00100: 48]-->ExceptionHandlerAbstract>>try:
[05D000FC: 47]-->a Process('Main' base 05D00000 [ACTIVE] in SessionManager>>quit: sp=00000000 ip=1 list=10050010)
[05D000F8: 46]-->a ExceptionHandler
[05D000F4: 45]-->[] @ 9 in BlockClosure>>ifCurtailed:
[05D000F0: 44]-->[] @ 17 in ExceptionHandlerAbstract>>try:
[05D000EC: 43]-->48758890
[05D000E8: 42]-->48758902
[05D000E4: 41]-->17
[05D000E0: 40]-->48758876
[05D000DC: 39]-->0
[05D000D8: 38]-->BlockClosure>>ifCurtailed:
[05D000D4: 37]-->[] @ 39 in ExceptionHandlerAbstract>>try:
[05D000D0: 36]-->[] @ 0 in nil
[05D000CC: 35]-->48758872
[05D000C8: 34]-->48758886
[05D000C4: 33]-->2
[05D000C0: 32]-->48758858
[05D000BC: 31]-->0
[05D000B8: 30]-->BlockClosure>>ensure:
[05D000B4: 29]-->nil
[05D000B0: 28]-->[] @ 39 in ExceptionHandlerAbstract>>try:
[05D000AC: 27]-->[] @ 17 in ExceptionHandlerAbstract>>try:
[05D000A8: 26]-->48758852
[05D000A4: 25]-->48758868
[05D000A0: 24]-->43
[05D0009C: 23]-->48758838
[05D00098: 22]-->a Context for: nil frame: 5d00095
[05D00094: 21]-->ExceptionHandlerAbstract>>try:
[05D00090: 20]-->a Process('Main' base 05D00000 [ACTIVE] in SessionManager>>quit: sp=00000000 ip=1 list=10050010)
[05D0008C: 19]-->nil
[05D00088: 18]-->[] @ 10 in InputState>>forkMain
[05D00084: 17]-->a ExceptionHandler
[05D00080: 16]-->48758834
[05D0007C: 15]-->48758848
[05D00078: 14]-->6
[05D00074: 13]-->48758820
[05D00070: 12]-->0
[05D0006C: 11]-->BlockClosure>>on:do:
[05D00068: 10]-->[] @ 13 in BlockClosure>>newProcess
[05D00064: 9]-->ProcessTermination
[05D00060: 8]-->[] @ 10 in InputState>>forkMain
[05D0005C: 7]-->48758820
[05D00058: 6]-->48758830
[05D00054: 5]-->16
[05D00050: 4]-->0
[05D0004C: 3]-->[] @ 9 in BlockClosure>>newProcess
[05D00048: 2]-->BlockClosure>>newProcess
[05D00044: 1]-->[] @ 10 in InputState>>forkMain
<Bottom of stack>

***** End of crash report *****
`

The version with the block being posted appears to exit without any problems.
I'm on W10. I've tested this a long time ago under 7 (64) and a vanilla image with the same results.

**Comment by objectarts** [comment]
I have changed the build and test scripts to get around this immediate issue so the PR now passes. I've filed [Dolphin Issue 57](https://github.com/dolphinsmalltalk/Dolphin/issues/57) although maybe this should be moved to DolphinVM depending on where the real problem lies.

**Comment by blairmcg** [comment]
Let's leave this pending for now. There is another image side problem with the CRT stdio streams that I need to fix first. Thanks

**Comment by blairmcg** [comment]
I'm about to push a change to revert the AppVeyor script change that Andy made to work around the problem with the boot failing due to an error code from the Dolphin on shutdown. If that passes, this is going in, and the VM will be a VS2015 project. Once that is done, all DolphinVM developers will need to be using VS2015 (free CE is fine).

**Pull request merged**
