### PR TITLE
Require full image name as first argument

### PR DESCRIPTION
**Pull request by jgfoster**
This PR looks at the startup argument name and adds the image suffix ('.img7') if it is missing. This allows one to launch Dolphin7.exe with 'DPRO' instead of 'DPRO.img7'. Given that the VM requires an image, .sml, and .chg it seems reasonable to reduce the typing overhead required.

Since I'm actually submitting new code with temp variables etc, I would welcome feedback and guidance about naming conventions and coding style. Is there some reference to point to? 

Finally, while changing the default image from 'Dolphin.img7' to 'DPRO.img7' is useful for us, it raises the question of image names. I wonder if DCORE and DCE are really needed. I appreciate the idea of moving toward a build up model rather than a tear down model (and have contributed some things that I think will eventually help in that direction), but don't see that the other two images are much use now. Perhaps the DPRO image ought to be renamed Dolphin and the prior default image name supported (some users might have scripts that rely on it).

Thanks!

### CODE REVIEW

**Comment by jgfoster** [comment]
@blairmcg, Thanks. I'll check it out.

**Comment by objectarts** [comment]
Sorry, @jgfoster but even with @blairmcg 's suggestion I still don't think I would be happy with this change. 

The problem is that we are splitting the responsibility of command line handling between the VM (here) and the image (where your recent additions give excellent service). Hence you are having here to make inferences about the purposes of the argv array contents that not only increases the complexity of this piece of code but also reduces the flexibility of what the command line handling in the image may subsequently decide to do. 

The other observation I would make is that invoking Dolphin without an image name parameter probably shouldn't be allowed at all. Or certainly not encouraged. The only reason I changed the default was to make invoking the debugger easier but that can of course be done by altering the project file anyway.

The first thing any **userdev** should do it to save the default image (as it stands, DPRO.img7) under a different name. Otherwise, you'll end up modifying what is essentially a system file and have to reinstall if you want to reset back to a known state. I'm writing a new Getting Started page that suggests this. If this step is followed then one should never need to invoke Dolphin7.exe on it's own. The correct way to start Dolphin should always be to double click an image file.

For the same reason I don't think it is necessary to change the booted image names. I agree that at some point DCE can probably go but DCORE and DPRO both convey information in the names more than DOLPHIN on its own would do. As I said before I believe DCORE is useful because it is intended to be the minimum possible working development image (it is currently too big and should probably be pared down in future). Changing the names to me is just "churn" (i.e. effort without commensurate reward) and would involve changing the product classes in the image, the website and the documentation.

With regard to variable naming, I'm not normally a fan of hungarian notation for it's own sake because surely the whole point about having a typed language is that you can always find the type with a single keystroke anyway. The exception to this, of course, is when the C++ type doesn't accurately reflect the "real" type of the variable. e.g. in the case of null terminated strings, it is useful to prefix the variable names with `sz` because this convey information that the C++ typing system does not. Other than that, I'd just name stuff as you would do in Smalltalk (not in the anInteger stye though).

**Comment by objectarts** [comment]
@jgfoster if there did turn out to be overwhelming enthusiasm for this change I think we should have to ditch the idea of a default image name and always insist that the first parameter in the command line is the image and it must always be present. That way the coding would be trivial and the parsing of the command line in the image would still be straightforward.

**Comment by objectarts** [comment]
Actually, @jgfoster, I think I've been a bit harsh here. If you still want to do this go ahead but with the suggestion above, i.e. that the image name **must** always be present as the first parameter. I think the in image code will need changing too.

**Comment by jgfoster** [comment]
@objectarts, thanks for the comments and the progression in the ideas. This isn't an area I feel strongly about at all. Mostly I tried `Dolphin7 DPRO` on the command line and it reported that the file did not exist. I figured that if the first argument (if present) is going to be treated as an image name then finding the right file is no worse than reporting an error! I viewed this as a very incremental change that addresses one narrow situation. I probably complicated the discussion by raising the issue of default names (my offered code doesn't address this issue at all). I'll go ahead and try @blairmcg's suggestion--mostly to learn more Windows coding. 

I can take out the default but don't see that it does any harm. The image code already ignores the first argument (if present) so there will be no impact on the image code. I was even thinking of presenting a File Open Dialog as an alternative to the default. Again, I'm mostly tweaking in a small area to get my toes in the water. I really don't have a vision of what this should do and welcome your guidance.

**Comment by objectarts** [comment]
Ok, I don't like the loop through all the args looking for a non flag. Can we ensure that the image if present must always be the first parameter. Even that I don't really like because both the VM and image have to _know_ that flags begin with / or -. But I can probably live with that I guess.

**Comment by jgfoster** [comment]
@blairmcg, I don't see that there is an ANSI version of [PathCchAddExtension](https://msdn.microsoft.com/en-us/library/windows/desktop/hh707080(v=vs.85).aspx) while there is one of  [PathAddExtension](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773563(v=vs.85).aspx). Thoughts?

**Comment by jgfoster** [comment]
Somehow the most recent edits appear to have much more diffs than I actually made. The short version is in `StartDevSys` starting at line 89:

`	if (__argc < 2)`
`		return ReportError(IDP_NOIMAGENAME);`

and then in `FindImageNameArg()` starting at line 30:

`	static char achImageName[_MAX_PATH];`
`	char* filePart;`
`	::GetFullPathName(__argv[1], _MAX_PATH, achImageName, &filePart);`
`	return achImageName;`

It turns out that using the built-in functions was more complicated (the basic one is deprecated and the complex one uses wide characters).

**Comment by blairmcg** [comment]
I'm OK with that if @objectarts is. It is certainly simple.

**Comment by jgfoster** [comment]
There seems to be enough uncertainty about what is wanted that I'll just close this.

**Pull request closed without merging**
