### PR TITLE
VM Debug now builds without errors

### PR DESCRIPTION
**Pull request by jgfoster**
It doesn't run very far (!), but the Release configuration build passes all 1800 tests.
Code changes include 'JGFoster' in the comment so you can see what was done.

### CODE REVIEW

**Comment by fxgallego** [comment]
@jgfoster this allows to run the VM with debugger support? I've taken another approach to this.

**Comment by objectarts** [comment]
@jgfoster, I'm note sure how this fits with the work @fxgallego has been doing. Can you two discuss this before I merge one or the other?

**Comment by jgfoster** [comment]
@fxgallego, yes, I can start Dolphin7.exe from within Visual Studio 2013 Professional. What approach are you taking?

**Comment by fxgallego** [comment]
@jgfoster I don't change any of the VM sources. I have created a "VM Debug 2" config copy of Release and changed all settings to debug. Doing that I can debug but I can't read locals in the debugger due to some wrong configuration.
I'll take your commit to see if It helps me to understand which compiler flags I've miss configured.

**Comment by jgfoster** [comment]
@fxgallego, I found that some edits were required. For example, consider `objmem.h:936`:
`	#if defined(_DEBUG) && defined(`
This line seems to end rather abruptly!
Then there are things like `Interpreter::AddVMReference` that are defined in `Interprt.h:111` and called from `IDolphin.cpp:53` but the code is missing.

So, yes, I made changes to the VM sources. And, yes, I can read locals in the debugger. There is certainly work to be done, but since it builds and the release version passes the tests, it seems like a good platform for forward progress.

**Comment by fxgallego** [comment]
Sure that the Release project has a some things excluded. Sorry I can't deny or approve your changes because I don´t know what could happen. It's good to know that you can read locals in the debugger so I'll try to get my config to work. Or if you have enough time maybe you can try to do the same to left the sources untouched, I have no problem. I'm currently with a lot of work because is my last week before vacation.

**Comment by jgfoster** [comment]
@objectarts, do you want me to pursue anything further with @fxgallego? It doesn't sound like he has time to go into much depth. Since he hasn't published any of his work I can't really comment further. I'm pretty confident about the state of the development tools started from the launcher (all 1800 tests pass). I don't know to what extent the existing tests cover the Console or ToGo components.

**Comment by objectarts** [comment]
@jgfoster, if @fxgallego is happy, I'll take a look at your changes.

**Comment by fxgallego** [comment]
@jgfoster, @objectarts Hey guys, I'm very happy :smile:
Please go ahead with this, I'll be watching this and help if I get some free time.

**Pull request merged**
